# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ddbc66644afce176d770d7a738ba55f2ed630c290340b6b2108b383d415aaeff641ce1e6a8bdea545dec4213a0a77bd4cf370e87bfb6140ccf071492778c409

test:
  secret_key_base: 331d2277e75021e31fa15703ba328afb4675c4f755991a6ba7bea2006f4d861fd76dbab8d7d446fdeed88499e855125e5e1248d49cf4ebeee5024667c48bbaf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
